# Generated by Django 5.1.3 on 2025-04-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_delete_category_alter_task_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
