# Generated by Django 5.1.3 on 2025-02-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='Users',
        ),
    ]
