# Generated by Django 5.1.3 on 2025-04-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('On hold', 'On hold'), ('Not started', 'Not started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not started', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10),
        ),
    ]
