# Generated by Django 5.1.6 on 2025-04-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
